const URL="https://xevkttwbzfosxmslnrku.supabase.co",KEY="sb_publishable_nqqizWWCx2Wztrdc1ya4XQ_BHaRWM0N",db=supabase.createClient(URL,KEY);
let user,me,products=[],shift=null;
const rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const e=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]));
const $=id=>document.getElementById(id), say=(id,t)=>$(id).textContent=t;
async function start(){let r=await db.auth.getSession();user=r.data.session?.user;if(!user)return deny("Silakan login dulu.");let q=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();if(q.error||!q.data)return deny("Profil tidak ditemukan.");me=q.data;if(!["owner","admin","staff"].includes(me.role)||!me.is_active)return deny("Akses ditolak. Khusus Owner/Admin/Staff.");$("access").hidden=true;$("app").hidden=false;tabs();buttons();await Promise.all([loadProducts(),dash(),orders(),customers(),payments(),moves(),shifts(),settings()])}
function deny(t){$("access").innerHTML="<strong>"+e(t)+"</strong><br><br><a href='./'>Kembali ke website</a>"}
function tabs(){document.querySelectorAll("#tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$(b.dataset.tab).hidden=false})}
function buttons(){$("logout").onclick=async()=>{await db.auth.signOut();location.href="./"};$("refreshDash").onclick=dash;$("period").onchange=dash;$("addProduct").onclick=()=>{$("productForm").hidden=false;clearP()};$("cancelProduct").onclick=()=>$("productForm").hidden=true;$("productForm").onsubmit=saveP;$("refreshOrders").onclick=orders;$("addMove").onclick=()=>$("moveForm").hidden=false;$("cancelMove").onclick=()=>$("moveForm").hidden=true;$("moveForm").onsubmit=saveMove;$("refreshCustomers").onclick=customers;$("customerSearch").oninput=customers;$("refreshPayments").onclick=payments;$("openShift").onclick=openShift;$("closeShift").onclick=closeShift;$("settingsForm").onsubmit=saveSettings}
async function loadProducts(){let r=await db.from("products").select("*").order("id",{ascending:false});if(r.error)return say("pmsg",r.error.message);products=r.data||[];$("activeProducts").textContent=products.filter(x=>x.is_active).length;$("stockCount").textContent=products.reduce((a,x)=>a+Number(x.stock||0),0);$("mproduct").innerHTML=products.map(x=>`<option value="${x.id}">${e(x.name)}</option>`).join("");$("productRows").innerHTML=products.map(p=>`<tr><td><b>${e(p.name)}</b></td><td>${e(p.sku||"-")}</td><td>${rp(p.price)}</td><td>${p.stock}</td><td>${p.is_active?"Aktif":"Nonaktif"}</td><td><button onclick="editP(${p.id})">Edit</button> <button class="danger" onclick="delP(${p.id})">Hapus</button></td></tr>`).join("")}
function clearP(){["pid","pname","psku","pprice","pcost","pstock","pmin","pdesc","pimage"].forEach(x=>$(x).value="");$("pactive").value="true"}
function editP(id){let p=products.find(x=>x.id==id);if(!p)return;$("productForm").hidden=false;$("pid").value=p.id;$("pname").value=p.name;$("psku").value=p.sku||"";$("pprice").value=p.price;$("pcost").value=p.cost_price;$("pstock").value=p.stock;$("pmin").value=p.min_stock;$("pdesc").value=p.description||"";$("pimage").value=p.image_url||"";$("pactive").value=String(p.is_active)}
async function saveP(ev){ev.preventDefault();let id=$("pid").value,name=$("pname").value.trim(),obj={name,sku:$("psku").value.trim()||null,description:$("pdesc").value.trim()||null,image_url:$("pimage").value.trim()||null,price:+$("pprice").value,cost_price:+$("pcost").value||0,stock:+$("pstock").value||0,min_stock:+$("pmin").value||0,is_active:$("pactive").value==="true"};let r=id?await db.from("products").update(obj).eq("id",id):await db.from("products").insert({...obj,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now()});if(r.error)return say("pmsg","Gagal: "+r.error.message);$("productForm").hidden=true;await loadProducts()}
window.delP=async id=>{if(confirm("Hapus produk ini?")){let r=await db.from("products").delete().eq("id",id);if(r.error)alert(r.error.message);else loadProducts()}}
async function dash(){let d=new Date(),p=$("period").value,s=new Date(d.getFullYear(),p==="year"?0:d.getMonth(),p==="day"?d.getDate():1),r=await db.from("orders").select("id,total_amount,status,created_at").gte("created_at",s.toISOString()).neq("status","cancelled");if(r.error)return;$("sales").textContent=rp((r.data||[]).reduce((a,x)=>a+Number(x.total_amount||0),0));$("orderCount").textContent=(r.data||[]).length}
async function orders(){let q=db.from("orders").select("*").order("created_at",{ascending:false}).limit(300),f=$("ofrom").value,t=$("oto").value,s=$("ostatus").value;if(f)q=q.gte("created_at",new Date(f+"T00:00:00").toISOString());if(t)q=q.lt("created_at",new Date(new Date(t+"T00:00:00").getTime()+86400000).toISOString());if(s)q=q.eq("status",s);let r=await q;$("orderRows").innerHTML=r.error?`<tr><td colspan=5>${e(r.error.message)}</td></tr>`:(r.data||[]).map(x=>`<tr><td>${e(x.order_number)}</td><td>${e(x.user_id)}</td><td>${e(x.status)}</td><td>${rp(x.total_amount)}</td><td>${new Date(x.created_at).toLocaleString("id-ID")}</td></tr>`).join("")}
async function moves(){let r=await db.from("inventory_movements").select("*").order("created_at",{ascending:false}).limit(300);$("moveRows").innerHTML=r.error?`<tr><td colspan=5>${e(r.error.message)}</td></tr>`:(r.data||[]).map(x=>{let p=products.find(y=>y.id==x.product_id);return`<tr><td>${e(p?.name||x.product_id)}</td><td>${e(x.type)}</td><td>${x.quantity}</td><td>${e(x.note||"-")}</td><td>${new Date(x.created_at).toLocaleString("id-ID")}</td></tr>`}).join("")}
async function saveMove(ev){ev.preventDefault();let id=+$("mproduct").value,q=+$("mqty").value,type=$("mtype").value,p=products.find(x=>x.id==id);if(!p)return;let stock=p.stock+(type==="in"?q:type==="out"?-q:q);if(stock<0)return say("mmsg","Stok tidak boleh minus.");let a=await db.from("inventory_movements").insert({product_id:id,type,quantity:q,note:$("mnote").value.trim()||null,created_by:user.id});if(a.error)return say("mmsg",a.error.message);let b=await db.from("products").update({stock}).eq("id",id);if(b.error)return say("mmsg",b.error.message);$("moveForm").hidden=true;await loadProducts();await moves()}
async function customers(){let r=await db.from("profiles").select("id,full_name,phone,role,is_active,created_at").order("created_at",{ascending:false}).limit(500),s=$("customerSearch").value.toLowerCase();let a=(r.data||[]).filter(x=>(`${x.full_name||""} ${x.phone||""} ${x.id}`).toLowerCase().includes(s));$("customerRows").innerHTML=r.error?`<tr><td colspan=5>${e(r.error.message)}</td></tr>`:a.map(x=>`<tr><td>${e(x.full_name||"-")}</td><td>${e(x.phone||"-")}</td><td>${e(x.role)}</td><td>${x.is_active?"Ya":"Tidak"}</td><td>${new Date(x.created_at).toLocaleDateString("id-ID")}</td></tr>`).join("")}
async function payments(){let q=db.from("payments").select("*").limit(500);let p=$("payPeriod").value,d=new Date(),s=p==="today"?new Date(d.getFullYear(),d.getMonth(),d.getDate()):p==="month"?new Date(d.getFullYear(),d.getMonth(),1):p==="year"?new Date(d.getFullYear(),0,1):null;if(s)q=q.gte("created_at",s.toISOString());let r=await q,rows=r.data||[];let sort=$("paySort").value;if(sort==="az")rows.sort((a,b)=>String(a.transaction_id||"").localeCompare(String(b.transaction_id||"")));if(sort==="date_asc")rows.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));if(sort==="date_desc")rows.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(sort==="amount_desc")rows.sort((a,b)=>b.amount-a.amount);$("payRows").innerHTML=r.error?`<tr><td colspan=6>${e(r.error.message)}</td></tr>`:rows.map(x=>`<tr><td>${e(x.transaction_id||"-")}</td><td>${x.order_id}</td><td>${e(x.payment_method||"-")}</td><td>${e(x.status)}</td><td>${rp(x.amount)}</td><td>${new Date(x.created_at).toLocaleString("id-ID")}</td></tr>`).join("")}
async function shifts(){let r=await db.from("shifts").select("*").order("opened_at",{ascending:false}).limit(200);if(r.error)return $("currentShift").textContent=r.error.message;let a=r.data||[];shift=a.find(x=>x.status==="open")||null;$("currentShift").innerHTML=shift?`<b>SHIFT AKTIF</b><br>Dibuka ${new Date(shift.opened_at).toLocaleString("id-ID")}<br>Order ${shift.total_orders} · Penjualan ${rp(shift.total_sales)}`:"Tidak ada shift aktif.";$("shiftRows").innerHTML=a.filter(x=>x.status==="closed").map(x=>`<tr><td>${new Date(x.opened_at).toLocaleString("id-ID")}</td><td>${x.closed_at?new Date(x.closed_at).toLocaleString("id-ID"):"-"}</td><td>${x.total_orders}</td><td>${rp(x.total_sales)}</td><td>${rp(x.total_discount)}</td><td><button onclick="editShift(${x.id})">Edit</button> <button class="danger" onclick="deleteShift(${x.id})">Hapus</button></td></tr>`).join("")}
async function openShift(){if(shift)return alert("Sudah ada shift aktif.");let r=await db.from("shifts").insert({opened_by:user.id,status:"open",opening_stock:products.reduce((a,x)=>a+Number(x.stock||0),0)});if(r.error)alert(r.error.message);else shifts()}
async function closeShift(){if(!shift)return alert("Tidak ada shift aktif.");let r=await db.from("orders").select("id,total_amount,discount_amount,shipping_fee,status").gte("created_at",shift.opened_at).neq("status","cancelled");if(r.error)return alert(r.error.message);let a=r.data||[],sales=a.reduce((s,x)=>s+Number(x.total_amount||0),0),disc=a.reduce((s,x)=>s+Number(x.discount_amount||0),0),stock=products.reduce((s,x)=>s+Number(x.stock||0),0);let u=await db.from("shifts").update({closed_by:user.id,closed_at:new Date().toISOString(),status:"closed",closing_stock:stock,total_orders:a.length,total_sales:sales,total_discount:disc,total_shipping:a.reduce((s,x)=>s+Number(x.shipping_fee||0),0)}).eq("id",shift.id);if(u.error)alert(u.error.message);else shifts()}
window.editShift=async id=>{let n=prompt("Catatan koreksi shift:");if(n===null)return;let r=await db.from("shifts").update({notes:n}).eq("id",id);if(r.error)alert(r.error.message);else shifts()}
window.deleteShift=async id=>{if(!confirm("Hapus riwayat shift ini?"))return;let r=await db.from("shifts").delete().eq("id",id);if(r.error)alert(r.error.message);else shifts()}
async function settings(){let r=await db.from("business_settings").select("*").eq("setting_key","store").maybeSingle(),v=r.data?.setting_value||{};$("sname").value=v.name||"";$("sphone").value=v.phone||"";$("saddress").value=v.address||"";$("sage").value=v.age||21;$("smode").value=v.mode||"open"}
async function saveSettings(ev){ev.preventDefault();let v={name:$("sname").value.trim(),phone:$("sphone").value.trim(),address:$("saddress").value.trim(),age:+$("sage").value||21,mode:$("smode").value};let r=await db.from("business_settings").upsert({setting_key:"store",setting_value:v,updated_by:user.id},{onConflict:"setting_key"});say("smsg",r.error?"Gagal: "+r.error.message:"Pengaturan tersimpan.")}
start();